tags:
  - name: "User"
    description: "Operations about user"
  - name: "Post"
    description: "Operations about posts"
paths:
  /user:
    post:
      tags:
        - "User"
      summary: "Add new user"
      consumes:
        - "application/json"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/User"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "User registred"
  /post:
    post:
      tags:
        - "Post"
      summary: "Add new post"
      consumes:
        - "application/json"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Post"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Post registred"
  /post/{post_id}/comment:
    post:
      tags:
        - "Post"
      summary: "Add new comment"
      consumes:
        - "application/json"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Comment"
      parameters:
        - in: "path"
          name: "post_id"
          required: true
          type: "integer"
          format: "int64"
          description: "Id of post"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Comment registred"
  /posts:
    get:
      tags:
        - "Post"
      summary: "get post in pagination"
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "page"
          type: "integer"
          format: "int64"
          description: "page of pagination"
        - in: "query"
          name: "width"
          type: "integer"
          format: "int64"
          description: "width of pagination"
        - in: "authorId"
          name: "width"
          type: "integer"
          format: "int64"
          description: "Author or user"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "pagination of posts"
  /post/{id}/comments:
    get:
      tags:
        - "Post"
      summary: "get comments of a post"
      consumes:
        - "application/json"
      
      parameters:
        - in: "path"
          name: "id"
          required: true
          type: "integer"
          format: "int64"
          description: "Id of post"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Comments of a post"
  /author/{id}/activities:
    get:
      tags:
        - "User"
      summary: "get activities of user"
      consumes:
        - "application/json"
      
      parameters:
        - in: "path"
          name: "id"
          required: true
          type: "integer"
          format: "int64"
          description: "Id of post"
      responses:
        "400":
          description: "Invalid input"
        "200":
          description: "Activities of a user"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      email:
        type: "string"
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      authorId:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      content:
        type: "string"
  Comment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        required: false
      authorId:
        type: "integer"
        format: "int64"
      content:
        type: "string"
